INSERT INTO CUSTOMER (customer_id, name) VALUES (1, 'Mateusz')
INSERT INTO CUSTOMER (customer_id, name) VALUES (2, 'Monika')
INSERT INTO CUSTOMER (customer_id, name) VALUES (3, 'Jan')

INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (1, '2024-03-25', 150, 1)
INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (2, '2024-03-22', 50, 1)
INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (3, '2024-02-01', 10, 1)
INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (4, '2023-06-25', 150, 1)
INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (5, '2024-03-25', 10, 2)
INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (6, '2024-03-25', 60, 2)
INSERT INTO TRANSACTION (transaction_id, transaction_date, transaction_amount, customer_id) VALUES (7, '2024-03-25', 49, 3)